name: patch-gnn
channels:
- conda-forge
dependencies:
- python=3.8
- biopandas>=0.2.7
- black>=20.8b1
- conda>=4.8.4
- coverage>=5.2.1
- flake8>=3.8.3
- interrogate>=1.3.1
- ipykernel>=5.3.4
- ipython>=7.18.1
- isort>=5.6.0  # has a bugfix that we need for imports sorted underneath docstring
- jax>=0.2.5
- jaxlib>=0.1.56
- jupyter>=1.0.0
- jupyterlab>=2.2.7
- mamba>=0.5.1
- matplotlib>=3.3.1
- mypy>=0.782
- nbconvert
- nbstripout>=0.3.9
- networkx>=2.5
- nodejs>=14.13.0
- numpy>=1.19.1
- pandas>=1.1.2
- pip>=20.2.3
- pre-commit>=2.7.1
- pycodestyle>=2.6.0
- pydocstyle>=5.1.1
- pyprojroot>=0.2.0
- pytest>=6.0.1
- pytest-cov>=2.10.1
- scikit-learn>=0.23.2
- scipy>=1.5.2
- xarray>=0.16.0
- pip:
  - mkdocs>=1.1.2
  - mkdocs-material>=6.0.2
  - mkdocstrings>=0.13.6
  - mknotebooks>=0.6.0
  - proteingraph>=0.3.0
